# Generated by Django 2.0.1 on 2018-01-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curencies',
            options={'ordering': ['first_currency_short'], 'verbose_name': 'Currency pairs', 'verbose_name_plural': 'Currency pairs'},
        ),
        migrations.AddField(
            model_name='curencies',
            name='first_currency_short',
            field=models.CharField(default='', max_length=5, verbose_name='First currency short'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curencies',
            name='second_currency_short',
            field=models.CharField(default='', max_length=5, verbose_name='Second currency short'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curencies',
            name='first_currency_long',
            field=models.CharField(max_length=15, verbose_name='First currency'),
        ),
        migrations.AlterField(
            model_name='curencies',
            name='second_currency_long',
            field=models.CharField(max_length=15, verbose_name='Second_currency'),
        ),
        migrations.AlterModelTable(
            name='curencies',
            table='currencies',
        ),
    ]
